
__include__: [
  '../dataset/uavdt.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

checkpoint_step: 36
output_dir: output/uavdt/rtdetr_r18vd_6x_uavdt_spbio
epoches: 240

RTDETR: 
  backbone: PResNet
  encoder: PBiEncoder
  decoder: O2MRTDETRTransformer

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

PBiEncoder:
  in_channels: [128, 256, 512]
  feat_strides: [8, 16, 32]

  # select
  spatial_select: True
  
  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1

  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  pe_temperature: 10000
  
  # cross
  expansion: 0.5
  depth_mult: 1
  act: 'silu'

  # eval
  eval_spatial_size: [640, 640]


O2MRTDETRTransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_queries: 300
  num_o2m_queries_k: 3

  num_decoder_layers: 3
  num_denoising: 100
  
  eval_idx: -1
  eval_spatial_size: [640, 640]


train_dataloader: 
  batch_size: 8
val_dataloader:
  batch_size: 8

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


criterion: SetmyCriterion

SetmyCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2,}
  losses: ['vfl', 'boxes', ]
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: DRMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    # use_focal_loss: True 
    alpha: 0.25
    gamma: 2.0

