__include__: [
  '../dataset/visdrone19.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]


checkpoint_step: 12
output_dir: output/rtdetr_r50vd_6x_visdrone
epoches: 144

train_dataloader: 
  batch_size: 3